name = "StructuredLight"
uuid = "13204c95-a6e5-4c09-8c7b-ee09b09e0944"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.1.4"

[deps]
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
StructuredLightCUDAExt = "CUDA"

[compat]
FourierTools = "0.4.2"
KernelAbstractions = ">= 0.8.6"
Tullio = "0.3.5"
julia = "1.10"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CUDA"]
